apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170296980
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170296980
    app.kubernetes.io/part-of: test-app-170296980
  name: java-quarkus-170296980
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170296980
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170296980
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170296980/java-quarkus-170296980@sha256:83fa1171b5b50f6e9b6605020d992e1fe0682e516e3443763e72528403eb27f6
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
